--liquibase formatted sql

--changeset DenisV:002-create-dish-recipe-table dbms:postgresql
CREATE TABLE IF NOT EXISTS dish_recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    unique_name VARCHAR(255) UNIQUE NOT NULL,
    recipe TEXT NOT NULL,
    ingredients JSONB NOT NULL
);
