--liquibase formatted sql

--changeset DenisV:003-create-transactions-table
CREATE TABLE IF NOT EXISTS item_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,
    transaction_amount BIGINT NOT NULL,
    transaction_currency VARCHAR(3) NOT NULL,
    item_id BIGINT NOT NULL,
    username VARCHAR(255) NOT NULL,
    transaction_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX transaction_uuid__status_idx ON item_transaction (uuid, transaction_status);
CREATE INDEX transaction_item_id_idx ON item_transaction (item_id);